# Generated by Django 3.0.3 on 2020-03-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='buzzer_status',
            field=models.IntegerField(default=1),
        ),
    ]
