# Generated by Django 3.0.3 on 2020-06-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200531_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='percentage',
            field=models.IntegerField(default=100),
        ),
    ]
